// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scraper} from '../models';

export function GetData(arg1:string):Promise<scraper.FinancialData>;
