// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData(arg1) {
  return window['go']['main']['App']['GetData'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function SaveCSV(arg1, arg2) {
  return window['go']['main']['App']['SaveCSV'](arg1, arg2);
}

export function OpenInExcel(arg1) {
  return window['go']['main']['App']['OpenInExcel'](arg1);
}
